### PR TITLE
Fixes tables dark mode

### PR DESCRIPTION
**Pull request by LucasTrg**
Fixes the tables that remained light in the dark mode

### CODE REVIEW

**Review by cgrigis — CHANGES_REQUESTED** [review]
It looks like the dark mode "active" lines no longer cover all the columns?

dark-mode

**Review by cgrigis — APPROVED** [review]

**Review by ineiti — APPROVED** [review]
Just following @cgrigis

**Comment by ineiti** [comment]
@LucasTrg - It should be in the `Ready4Merge` pipeline of the C4DT project... do you have permissions to add it to the Engineers' TODO project?

**Comment by LucasTrg** [comment]
Sorry about that, it's fixed now !

**Pull request merged**
