### PR TITLE
SalatéLab update

### PR DESCRIPTION
**Pull request by tharvik**
Also rename from SLAB.

### CODE REVIEW

**Review by cgrigis — APPROVED** [review]
LGTM

**Comment by ineiti** [comment]
Why doesn't github recognize this as a rename/move? Strange...

Also, the 00's called and asked me if the `é` is not poised to pose problems somewhere down the road... Should we play it safe and call it `SalatheLab`?

**Review by ineiti — COMMENTED** [review]
Why doesn't github recognize this as a rename/move? Strange...

Also, the 00's called and asked me if the `é` is not poised to pose problems somewhere down the road... Should we play it safe and call it `SalatheLab`?

**Comment by tharvik** [comment]
> Why doesn't github recognize this as a rename/move? Strange...

I think that's because of the numerous changes to the file, it is tagged as a renaming iff around 80% of the file is unchanged

> Also, the 00's called and asked me if the `é` is not poised to pose problems somewhere down the road... Should we play it safe and call it `SalatheLab`?

It shouldn't, if it does cause problems, then that might indicate bad handling of data that we can then fix :)

**Pull request merged**
