### PR TITLE
Use c4dt.css from @c4dt/angular-components

### LINKED ISSUE #183: Use the CSS provided by angular-components
After the new release from c4dt/angular-components#10, use its `c4dt.css`.

### PR DESCRIPTION
**Pull request by cgrigis**
Use the `c4dt.css` file provided by https://github.com/c4dt/angular-components.

Closes #183

### CODE REVIEW

**Comment by cgrigis** [comment]
Needs to be revisited after c4dt/angular-components#11 is merged

**Comment by cgrigis** [comment]
This probably needs to be reworked, and parts of it (the `@media (prefers-color-scheme: light) {` section) moved to https://github.com/c4dt/angular-components. I am not sure about the impact on pages using the @c4dt/angular-components for the  breadcrumbs though (the demo pages).
@LucasTrg You certainly have a better overall view of the styling of C4DT apps, I'll let you look at it when you have a moment. :)

**Comment by ineiti** [comment]
@cgrigis @tharvik shall we still merge this PR as-is? Or throw it away?

**Comment by cgrigis** [comment]
As I recall, the code to use the common CSS from `@c4dt/angular-components` is functional, but the split between those styles and the ones defined in the showcase, as well as the impact on all the other users of those styles (breadcrumbs, demos), need to be reworked.

**Pull request closed without merging**
