### PR TITLE
Update hexhive

### PR DESCRIPTION
**Pull request by tharvik**
* udate pass by https://github.com/c4dt/showcase/issues/136
* made a prettier pass, the "real" updates are in the second commit

I was unable to update GAENlib, as I don't have access to the private github. There isn't any paper on it in HexHive but maybe the `date_last_commit` needs to be updated, @cgrigis?

### CODE REVIEW

**Comment by cgrigis** [comment]
Good point. Actually, the private GitHub project is not really where the source code is, but rather where the project is tracked.
The source code is currently in two repos (forks with our branch), but we can probably put in the showcase the one for the app:
https://github.com/c4dt/dp3t-app-android-ch/tree/microg-nearby

**Comment by tharvik** [comment]
I've updated it with the OS repo link and rebased on the new master.

**Comment by tharvik** [comment]
@ineiti do you want to look at the updates? I'll merge it afterward

**Comment by ineiti** [comment]
All good for me, thanks for waiting - else I will never read about all my typos ;)

**Comment by ineiti** [comment]
Btw - we should `prettier` to the github-workflows.

**Comment by tharvik** [comment]
> Btw - we should `prettier` to the github-workflows.

Agreed, followed in https://github.com/c4dt/showcase/issues/144

And merging HexHive's updates :)

**Pull request merged**
